INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Jun', 'Mari','1981-06-01', 'M', 'CEO');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Kor', 'Mari','1983-01-30', 'F', 'President');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Ariel', 'Nota','1986-05-15', 'M', 'Chairman');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Mat', 'Pabi','1992-01-23', 'M', 'Chairman');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Chel', 'Almo','1993-11-30', 'F', 'Supervisor');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Aira', 'Pabi','1984-12-26', 'F', 'Team Lead');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Kyerr', 'Cruz','1968-05-09', 'M', 'Team Lead');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Karen', 'Viray','2000-07-18', 'F', 'Team Lead');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Zoren', 'Bay','2001-08-19', 'M', 'Owner');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Hero', 'Jaykot','1981-06-01', 'M', 'Vice-Chair');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Mots', 'Kamo','1983-01-30', 'M', 'Manager');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Eu', 'Gene','1986-05-15', 'M', 'Developer');
INSERT INTO IDENTIFICATION (FIRST_NAME, LAST_NAME, DOB, GENDER, TITLE) VALUES ('Ai', 'Leen','1992-01-23', 'F', 'Developer');


INSERT INTO ADDRESS (IDENTIFICATION_ID, TYPE, NUMBER, STREET, UNIT, CITY, STATE, ZIPCODE) VALUES (1, 'HOME', '1001', 'Sesame Street', 'Unit 1001', 'Elmo City', 'NY', '15001');
INSERT INTO ADDRESS (IDENTIFICATION_ID, TYPE, NUMBER, STREET, UNIT, CITY, STATE, ZIPCODE) VALUES (1, 'OFFICE', '1002', 'Azaki St.', 'Unit 1002', 'Arc City', 'CA', '90001');
INSERT INTO ADDRESS (IDENTIFICATION_ID, TYPE, NUMBER, STREET, UNIT, CITY, STATE, ZIPCODE) VALUES (2, 'HOME', '3001', 'ViewSonic Street', 'Unit 5B', 'Quartz City', 'DC', '25001');
INSERT INTO ADDRESS (IDENTIFICATION_ID, TYPE, NUMBER, STREET, UNIT, CITY, STATE, ZIPCODE) VALUES (3, 'HOME', '4001', 'Korna St.', 'Unit 100C', 'City of Angels', 'CA', '9003');
INSERT INTO ADDRESS (IDENTIFICATION_ID, TYPE, NUMBER, STREET, UNIT, CITY, STATE, ZIPCODE) VALUES (4, 'OFFICE', '5001', '3D Street', 'Unit 3D', 'Elec City', 'PA', '15015');
INSERT INTO ADDRESS (IDENTIFICATION_ID, TYPE, NUMBER, STREET, UNIT, CITY, STATE, ZIPCODE) VALUES (4, 'HOME', '5002', '3C Street', 'Unit 3C', 'Pewter City', 'AS', '17560');

INSERT INTO COMMUNICATION (IDENTIFICATION_ID, TYPE, VALUE, PREFERRED) VALUES (1, 'CELL', '09171112222', 'Y');
INSERT INTO COMMUNICATION (IDENTIFICATION_ID, TYPE, VALUE, PREFERRED) VALUES (1, 'EMAIL', 'email1@gmail.com', 'N');
INSERT INTO COMMUNICATION (IDENTIFICATION_ID, TYPE, VALUE, PREFERRED) VALUES (1, 'LANDLINE', '0271001200', 'N');
INSERT INTO COMMUNICATION (IDENTIFICATION_ID, TYPE, VALUE, PREFERRED) VALUES (2, 'EMAIL', 'eamil2@gmail.com', 'N');
INSERT INTO COMMUNICATION (IDENTIFICATION_ID, TYPE, VALUE, PREFERRED) VALUES (2, 'LANDLINE', '0281008888', 'N');
INSERT INTO COMMUNICATION (IDENTIFICATION_ID, TYPE, VALUE, PREFERRED) VALUES (3, 'CELL', '09181112200', 'Y');
INSERT INTO COMMUNICATION (IDENTIFICATION_ID, TYPE, VALUE, PREFERRED) VALUES (4, 'CELL', '09281112201', 'Y');
INSERT INTO COMMUNICATION (IDENTIFICATION_ID, TYPE, VALUE, PREFERRED) VALUES (5, 'CELL', '09291112202', 'Y');
